### ISSUE TITLE
无法刷新cookies

### ISSUE THREAD

**Issue by dfmjndm** [trojblue/TSDM-coin-farmer#15]
**描述**:无法刷新cookies,，使用的chrome和driver的版本均匹配

**平台**:centos

**产生方法**:python3.9 farm.py -r

**相关代码/commit**:

**错误报告等**:

[root@VM-8-2-centos src]# python3.9 farmer.py -r
刷新cookie
Traceback (most recent call last):
  File "/TSDM-coin-farmer/src/farmer.py", line 83, in <module>
    do_parse()
  File "/TSDM-coin-farmer/src/farmer.py", line 36, in do_parse
    get_cookies_tsdm_all()
  File "/TSDM-coin-farmer/src/lib/model.py", line 110, in get_cookies_tsdm_all
    get_cookie_tsdm(i[0], i[1])
  File "/TSDM-coin-farmer/src/lib/model.py", line 74, in get_cookie_tsdm
    driver = get_webdriver()
  File "/TSDM-coin-farmer/src/lib/model.py", line 206, in get_webdriver
    driver = webdriver.Chrome(chrome_options=options)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5634f5c27b13 <unknown>
#1 0x5634f5a2e688 <unknown>
#2 0x5634f5a52f1f <unknown>
#3 0x5634f5a4e5aa <unknown>
#4 0x5634f5a8964a <unknown>
#5 0x5634f5a837a3 <unknown>
#6 0x5634f5a590ea <unknown>
#7 0x5634f5a5a225 <unknown>
#8 0x5634f5c6f2dd <unknown>
#9 0x5634f5c732c7 <unknown>
#10 0x5634f5c5922e <unknown>
#11 0x5634f5c740a8 <unknown>
#12 0x5634f5c4dbc0 <unknown>
#13 0x5634f5c906c8 <unknown>
#14 0x5634f5c90848 <unknown>
#15 0x5634f5caac0d <unknown>
#16 0x7f89193e31ca <unknown>

**Comment by dfmjndm** [comment]
headless模式解决了
