### ISSUE TITLE
'WebDriver' object has no attribute 'find_element_by_xpath'

### ISSUE THREAD

**Issue by dfmjndm** [trojblue/TSDM-coin-farmer#16]
刷新cookies出现如下错误

[root@VM-8-2-centos src]# python3.9 farmer.py -r
刷新cookie
Traceback (most recent call last):
  File "/TSDM-coin-farmer/src/farmer.py", line 83, in <module>
    do_parse()
  File "/TSDM-coin-farmer/src/farmer.py", line 36, in do_parse
    get_cookies_tsdm_all()
  File "/TSDM-coin-farmer/src/lib/model.py", line 110, in get_cookies_tsdm_all
    get_cookie_tsdm(i[0], i[1])
  File "/TSDM-coin-farmer/src/lib/model.py", line 76, in get_cookie_tsdm
    driver.find_element_by_xpath("//*[starts-with(@id,'cookietime_')]").click()
AttributeError: 'WebDriver' object has no attribute 'find_element_by_xpath'

**Comment by dfmjndm** [comment]
find_element_by_方法在新版selenium中废弃，已修改成新版格式
